# alembic.ini
[alembic]
# Путь к директории с миграциями (versions и env.py)
script_location = alembic

# Строка подключения к БД (можно оставить пустой — берётся из env)
# sqlalchemy.url = driver://user:pass@host/db

# Другие настройки (опционально)
file_template = %%(rev)s_%%(slug)s
truncate_slug_length = 40
revision_environment = true

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S